hybrid: True
dataset_folder_path: 'Tetris'
batch_size : 40
kernel_size: 2
feature_map : 'zz'
ansatz : 'real_amplitudes'
feature_map_reps : 1
ansatz_reps : 1
show_circuit : True
loss_function : 'MSE'
epochs : 400
learning_rate: 0.01
csv_path : 'noiseless.csv'

hydra:
  sweep:
    dir: multirun
    subdir: ${hydra.job.override_dirname}